# site properties and page defaults
title: 机甲大师
subtitle: GIRT
description: 破茧而出，志在千里
header: images/fengmian.jpg
header-video: images/bgvideo.mp4
footer: images/fengmian.jpg
proofer: false
slogan: 破茧而出，志在千里
# site social media and other links
links:
  dy: https://www.douyin.com/user/MS4wLjABAAAAmmWk0bMWV7I9ZvIZdmgxaO2QUnXP_Q8BWh7-PFI9Xmz1zr3ot8kPlA5Iyg6fX-4H?from_tab_name=main
  github: tianai321DESCRIPTION=An engaging 1-3 sentence description of your lab.
  bilibili: https://space.bilibili.com/337318265?spm_id_from=333.1387.follow.user_card.click
  wechat: https://mp.weixin.qq.com/s/y8DGvpIOlJLTm5B4L2qsig
## jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  - scope:
      type: "awards"
    values:
      layout: award
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
  - scope:
      type: "news"
    values:
      layout: post



collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true
  awards:
    output: true
  news:
    output: true
  projects:
    output: true
  patents:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
